package com.baiyi.cratos.eds.dingtalk;

import com.baiyi.cratos.domain.generator.EdsAsset;
import com.baiyi.cratos.domain.generator.EdsAssetIndex;
import com.baiyi.cratos.eds.BaseEdsTest;
import com.baiyi.cratos.eds.core.config.EdsConfigs;
import com.baiyi.cratos.eds.dingtalk.model.DingtalkDepartmentModel;
import com.baiyi.cratos.eds.dingtalk.param.DingtalkDepartmentParam;
import com.baiyi.cratos.eds.dingtalk.repo.DingtalkDepartmentRepo;
import com.baiyi.cratos.service.EdsAssetIndexService;
import com.baiyi.cratos.service.EdsAssetService;
import com.google.common.base.Splitter;
import jakarta.annotation.Resource;
import org.junit.jupiter.api.Test;

import java.util.List;

import static com.baiyi.cratos.eds.core.constants.EdsAssetIndexConstants.USER_MAIL;

/**
 * &#064;Author  baiyi
 * &#064;Date  2025/8/12 18:04
 * &#064;Version 1.0
 */
public class MyEdsDingtalkTest extends BaseEdsTest<EdsConfigs.Dingtalk> {

    @Resource
    private DingtalkDepartmentRepo dingtalkDepartmentRepo;

    public static final String MAIL_LIST = """
            yuwen.sun@palmpay-inc.com
            huan.wu@palmpay-inc.com
            zejia.liu@palmpay-inc.com
            mengyuan.ying@palmpay-inc.com
            feng.ren@palmpay-inc.com
            abakpa.blessing@palmpay-inc.com
            anyaogu.josephine@palmpay-inc.com
            yuanyuan.chu@palmpay-inc.com
            oguche.glory@palmpay-inc.com
            oluwole.akintemi@palmpay-inc.com
            yuanyuan.wang@palmpay-inc.com
            folafunmi.ojo@palmpay-inc.com
            Philip.obiano@palmpay-inc.com
            terdoo.or@palmpay-inc.com
            samuel.lenson@palmpay-inc.com
            yifan.he@palmpay-inc.com
            yonghui.su@palmpay-inc.com
            haitao.lv@palmpay-inc.com
            okpara.chinwendu@palmpay-inc.com
            anifat.amuletiko@palmpay-inc.com
            bawa.abraham@palmpay-inc.com
            andreas.nonso@palmpay-inc.com
            fuwei.ruan@palmpay-inc.com
            adetomiwa.abiola@palmpay-inc.com
            danping.yin@palmpay-inc.com
            oluwaseun.osunkalu@palmpay-inc.com
            akinde.oluwakayode@palmpay-inc.com
            xinru.chen@palmpay-inc.com
            siheng.zhao@palmpay-inc.com
            shunyuan.zheng@palmpay-inc.com
            sui.yu@palmpay-inc.com
            fa.ying@palmpay-inc.com
            oyegbile.oluwatosin@palmpay-inc.com
            Michael.omosebi@palmpay-inc.com
            tanigbola.naheemah@palmpay-inc.com
            xiaolan.huang@palmpay-inc.com
            simon.iriah@palmpay-inc.com
            doubeni.princewill@palmpay-inc.com
            shiting.bai@palmpay-inc.com
            friday.ogungbemi@palmpay-inc.com
            oyindamola.lawal@palmpay-inc.com
            onyinyechi.opara@palmpay-inc.com
            zhe.li@palmpay-inc.com
            ruoxuan.wang@palmpay-inc.com
            olaniyi.olayinka@palmpay-inc.com
            aninze.Onyenashia@palmpay-inc.com
            oladipo.farounbi@palmpay-inc.com
            gonese.anthony@palmpay-inc.com
            han.wu@palmpay-inc.com
            ajayi.oyindamola@palmpay-inc.com
            damilola.adeyanju1@Palmpay-inc.com
            aitafo.samuel@palmpay-inc.com
            jianing.wu@palmpay-inc.com
            adeola.yemi@palmpay-inc.com
            abdul.yunusa@palmpay-inc.com
            daniel.benson@palmpay-inc.com
            chinonso.ogu@palmpay-inc.com
            adewale.iyanuoluwa@palmpay-inc.com
            aiyudu.omoruyi@palmpay-inc.com
            allen.ayonbi@palmpay-inc.com
            james.adewuyi@palmpay-inc.com
            adebowale.afolashade@palmpay-inc.com
            xiaoyang.li@palmpay-inc.com
            pan.wang@palmpay-inc.com
            adeoye.abiodun@palmpay-inc.com
            morenike.igene@palmpay-inc.com
            yanxia.wang@palmpay-inc.com
            abigael.akpobasa@palmpay-inc.com
            bukola.adesina@palmpay-inc.com
            Kareem.ayodele@palmpay-inc.com
            simisola.onasogun@palmpay-inc.com
            iboro.etukudoh@palmpay-inc.com
            uzodinma.okoye@palmpay-inc.com
            akinwande.gboluwaga@palmpay-inc.com
            sadiq.ayuba@palmpay-inc.com
            nduanusi.chinwendu@palmpay-inc.com
            elisha.odedoyin@palmpay-inc.com
            jianjun.li@palmpay-inc.com
            chao.yu@palmpay-inc.com
            eguonor.okode@palmpay-inc.com
            nwajuo.athnasius@palmpay-inc.com
            maryanne.mgbeme@palmpay-inc.com
            olagoke.oluwabori@palmpay-inc.com
            oluwasegun.alagbe@palmpay-inc.com
            onileere.adetoun@palmpay-inc.com
            somoye.paul@palmpay-inc.com
            timothy.chituru@palmpay-inc.com
            adegbite.esther@palmpay-inc.com
            lawal.abisola@palmpay-inc.com
            collins.nwoke@palmpay-inc.com
            dorcas.onogwu@palmpay-inc.com
            trinity.davids@palmpay-inc.com
            ezecyril.jennifer@palmpay-inc.com
            seun.adebayo@palmpay-inc.com
            okpe.gladys@palmpay-inc.com
            ruiyun.zhou@palmpay-inc.com
            olusola.abiodun@palmpay-inc.com
            afolabi.owatemi@palmpay-inc.com
            mbara.amarachi@palmpay-inc.com
            titilope.komolafe@palmpay-inc.com
            hotonu.abimbola@palmpay-inc.com
            adepoju.rebecca@palmpay-inc.com
            kafayat.okewale@palmpay-inc.com
            angela.chizoba@palmpay-inc.com
            ayomide.oloyede@palmpay-inc.com
            ella.blessing@palmpay-inc.com
            isah.habibah@palmpay-inc.com
            okomi.ebidisere@palmpay-inc.com
            tobi.ogunlana@palmpay-inc.com
            tochukwu.nwankwo@palmpay-inc.com
            ayok.magaji@palmpay-inc.com
            bilal.barau@palmpay-inc.com
            jude.effiong1@palmpay-inc.com
            tunde.olatunji@palmpay-inc.com
            jing.pan@palmpay-inc.com
            ogunlusi.oluwaseun@palmpay-inc.com
            okororie.lorrita@palmpay-inc.com
            linlin.zhang@palmpay-inc.com
            aleko.marcus@palmpay-inc.com
            anyanwu.collins@palmpay-inc.com
            prosper.ebigbo@palmpay-inc.com
            hassan.alimot@palmpay-inc.com
            dodeye.edet@palmpay-inc.com
            faith.odianose@palmpay-inc.com
            fatoba.oluwapelumi@palmpay-inc.com
            xin.yu@palmpay-inc.com
            oniga.innocent@palmpay-inc.com
            matthew.okos@palmpay-inc.com
            ugochukwu.onyekachi@palmpay-inc.com
            awhana.micheal@palmpay-inc.com
            uwem.asuquo@palmpay-inc.com
            tosin.adenekan@palmpay-inc.com
            amali.igbe@palmpay-inc.com
            anosike.prosper@palmpay-inc.com
            fadugba.abiodun@palmpay-inc.com
            funmilayo.ajagun@palmpay-inc.com
            omotoye.precious@palmpay-inc.com
            Taiwo.Ogunniyi@palmpay-inc.com
            liberty.amos@palmpay-inc.com
            ikuvwera.blessing@palmpay-inc.com
            olubanke.daniel@palmpay-inc.com
            blessing.uzoigwe@palmpay-inc.com
            qin.liu@palmpay-inc.com
            nwogu.esther@palmpay-inc.com
            temiloluwa.kehinde@palmpay-inc.com
            bamigbala.toba@palmpay-inc.com
            Ifeanyi.okwuka@palmpay-inc.com
            ikenna.nwanedo@palmpay-inc.com
            williams.awajiya@palmpay-inc.com
            amaris.christopher@palmpay-inc.com
            tingyue.gu@palmpay-inc.com
            paul.olawoye@palmpay-inc.com
            Adeiyongo.aondongu@palmpay-inc.com
            adeoye.helen@palmpay-inc.com
            abdulmuiz.abdulquadri@palmpay-inc.com
            adebayo.adenike@palmpay-inc.com
            adesuyi.opeyemi@palmpay-inc.com
            agbe.adebisi@palmpay-inc.com
            ajagun.marianna@palmpay-inc.com
            ajiferuke.ayodeji@palmpay-inc.com
            anthony.onu@palmpay-inc.com
            ikebudu.nneka@palmpay-inc.com
            kehinde.susan@palmpay-inc.com
            olamide.bilesanmi@palmpay-inc.com
            onatolu.felix@palmpay-inc.com
            joseph.praise@palmpay-inc.com
            ajagun.omolara@palmpay-inc.com
            nwuga.leonard@palmpay-inc.com
            omotolani.oladapo@palmpay-inc.com
            rekpene.divine@palmpay-inc.com
            akinsola.oyindamola@palmpay-inc.com
            onah.onukwube@palmpay-inc.com
            takon.anaba@palmpay-inc.com
            akano.olawale@palmpay-inc.com
            fatai.lasisi@palmpay-inc.com
            israel.james@palmpay-inc.com
            oche.eche@palmpay-inc.com
            olumide.kafaru1@palmpay-inc.com
            igwe.nkachu@palmpay-inc.com
            Chibueze.uwalaka@palmpay-inc.com
            abdulwahab.tolulope@palmpay-inc.com
            adejimi.abosede@palmpay-inc.com
            afinnih.habeeb@palmpay-inc.com
            ajibola.hellen@palmpay-inc.com
            emeka.omeogha@palmpay-inc.com
            gift.okemezie@palmpay-inc.com
            ishola.omowunmi@palmpay-inc.com
            itaman.matthew@palmpay-inc.com
            katherine.anuore@palmpay-inc.com
            lawal.abdulqudus@palmpay-inc.com
            lucy.egwuatu@palmpay-inc.com
            oluwasanmi.aramide@palmpay-inc.com
            sopuruchi.nwokocha@palmpay-inc.com
            adeyemi.oluwagbemiga@palmpay-inc.com
            bajomo.felix@palmpay-inc.com
            collins.faith@palmpay-inc.com
            godwin.julian@palmpay-inc.com
            ifeoluwa.ilori@palmpay-inc.com
            niimatu.abu@palmpay-inc.com
            Odu.okwudili@palmpay-inc.com
            odusoga.zainab@palmpay-inc.com
            chenqian.zhou@palmpay-inc.com
            abraham.itodo@palmpay-inc.com
            jindi.zhang@palmpay-inc.com
            ng_channelsmonitor1@palmpay-inc.com
            oladeji.alao@palmpay-inc.com
            uche.elisha@palmpay-inc.com
            ikechukwu.mosesmaiyaki@palmpay-inc.com
            zhiqiang.zhang@palmpay-inc.com
            ayomide.olajide@palmpay-inc.com
            christianah.godonu@palmpay-inc.com
            folami.omotolani@palmpay-inc.com
            Okeke.Helen@palmpay-inc.com
            uche.ogechukwu@palmpay-inc.com
            yetunde.afolabi@palmpay-inc.com
            abdulsalam.khadijat@palmpay-inc.com
            arogbo.olawunmi@palmpay-inc.com
            ebunoluwa.opeyemi@palmpay-inc.com
            ikhide.kehinde@palmpay-inc.com
            itunuayo.Dada@palmpay-inc.com
            eloh.dorcas@palmpay-inc.com
            adeniran.oluwaseun@palmpay-inc.com
            adebayo.titilayo@palmpay-inc.com
            hamza.yahaya@palmpay-inc.com
            orobosa.ozue@palmpay-inc.com
            timothy.akaakase@palmpay-inc.com
            daniel.abugala@palmpay-inc.com
            fadeyiye.adebowale@palmpay-inc.com
            zhenyang.xu@palmpay-inc.com
            onuoha.judith@palmpay-inc.com
            adeagbo.temitope@palmpay-inc.com
            afolayan.oluwatofunmi@palmpay-inc.com
            emmanuella.nwabuokei@palmpay-inc.com
            okere.ijeoma@palmpay-inc.com
            oludele.ibukunoluwa@palmpay-inc.com
            olushola.loko@palmpay-inc.com
            peter.ojoba@palmpay-inc.com
            raji.oyelola@palmpay-inc.com
            shukurah.owolabi@palmpay-inc.com
            okeke.alexander@palmpay-inc.com
            olamide.dawodu@palmpay-inc.com
            john.maureen@palmpay-inc.com
            olasunkanmi.samson@palmpay-inc.com
            bitrus.madube@palmpay-inc.com
            eugenia.ejah@palmpay-inc.com
            oluwaseun.thomas@palmpay-inc.com
            timothy.ilori@palmpay-inc.com
            ubom.precious@palmpay-inc.com
            paul.omachi@palmpay-inc.com
            ezekiel.uwodi@palmpay-inc.com
            chiye.wang@palmpay-inc.com
            adedayo.aderinto@palmpay-inc.com
            oluwadara.olowolayemo@palmpay-inc.com
            agbemiro.victor@palmpay-inc.com
            christiana.oladokun@palmpay-inc.com
            okechukwu.ogbonna@palmpay-inc.com
            oladipupo.deborah@palmpay-inc.com
            olagunju.olabisi@palmpay-inc.com
            rukayat.olayiwola@palmpay-inc.com
            mengting.li@palmpay-inc.com
            dahunsi.oluwatosin@palmpay-inc.com
            idowu.emmanuel@palmpay-inc.com
            ayoola.jeremiah@palmpay-inc.com
            oyekunle.fafemi@palmpay-inc.com
            chinasa.azodo@palmpay-inc.com
            akpan.peace@palmpay-inc.com
            doris.asabuodu@palmpay-inc.com
            vincent.patrick@palmpay-inc.com
            adenopo.ridwan@palmpay-inc.com
            idehen.elizabeth@palmpay-inc.com
            abolarinwa.abigeal@palmpay-inc.com
            achio.jeniffer@palmpay-inc.com
            awe.oluwaseun@palmpay-inc.com
            ayinde.victoria@palmpay-inc.com
            ezehmoses.victoria@palmpay-inc.com
            momoh.mariam@palmpay-inc.com
            odeyemi.oluwakemi@palmpay-inc.com
            ogbechie.esther@palmpay-inc.com
            oladeji.nelson@palmpay-inc.com
            ruth.oyoke@palmpay-inc.com
            bolanle.ajayi@palmpay-inc.com
            fadiran.john@palmpay-inc.com
            rodiyat.toheeb@palmpay-inc.com
            ghomorai.jennifer@palmpay-inc.com
            lilian.enodegbe@palmpay-inc.com
            mayowa.ayodele@palmpay-inc.com
            olaide.akinola@palmpay-inc.com
            adesewa.akinduro@palmpay-inc.com
            olalekan.adekunle@palmpay-inc.com
            olorunnowo.olatoro@palmpay-inc.com
            ajibulu.olamide@palmpay-inc.com
            christiana.papka@palmpay-inc.com
            ayobami.falaju@palmpay-inc.com
            abraham.omoyayi@palmpay-inc.com
            adaba.khadijat@palmpay-inc.com
            ego.jane@palmpay-inc.com
            adenike.ogunsanya@palmpay-inc.com
            blessing.godwin@palmpay-inc.com
            chidinma.nnadi@palmpay-inc.com
            egenti.ekenedilichukwu@palmpay-inc.com
            lajuwomi.mary@palmpay-inc.com
            ojekunle.oluwabunmi@palmpay-inc.com
            oraekwute.kenechukwu@palmpay-inc.com
            oyeleso.adeola@palmpay-inc.com
            adebayo.abiodun@palmpay-inc.com
            igietsemhe.moses@palmpay-inc.com
            ojeikere.blessing@palmpay-inc.com
            jamiu.adebisi@palmpay-inc.com
            rosemary.akuh@palmpay-inc.com
            kemi.ayileka@palmpay-inc.com
            ojumu.olabisi@palmpay-inc.com
            joshua.oladokun@palmpay-inc.com
            kene.maduka@palmpay-inc.com
            adebare.beauty@palmpay-inc.com
            blessing.alagba@palmpay-inc.com
            grace.akinpelu@palmpay-inc.com
            jayeola.esther@palmpay-inc.com
            mirabel.akudinobi@palmpay-inc.com
            nafisat.nuraini@palmpay-inc.com
            Adikemere.felix@palmpay-inc.com
            sikiru.mojeed@palmpay-inc.com
            yihui.zhou@palmpay-inc.com
            dorcas.emeje@palmpay-inc.com
            qihang.feng@palmpay-inc.com
            elizabeth.asije@palmpay-inc.com
            idayat.suleiman@palmpay-inc.com
            maryam.idris@palmpay-inc.com
            sebastian.uche@palmpay-inc.com
            omowunmi.itogbe@palmpay-inc.com
            liang.zhan@palmpay-inc.com
            haoyu.wang@palmpay-inc.com
            lingli.li@palmpay-inc.com
            samuel.kpamber@palmpay-inc.com
            ajoke.salaam@palmpay-inc.com
            ayekolu.esther@palmpay-inc.com
            lawal.omolayo@palmpay-inc.com
            lawrence.david@palmpay-inc.com
            dolapo.adewunmi@palmpay-inc.com
            soyoye.feyisayo@palmpay-inc.com
            oluwaseun.adebayo@palmpay-inc.com
            agbelese.morenike@palmpay-inc.com
            Blessing.adikemere@palmpay-inc.com
            ezechikwelu.chinenye@palmpay-inc.com
            ezekiel.joy@palmpay-inc.com
            uzoma.chidinma@palmpay-inc.com
            abolaji.damola@palmpay-inc.com
            chiamaka.erondu@palmpay-inc.com
            Ogun.feyisola@palmpay-inc.com
            otorigra.joyce@palmpay-inc.com
            shobanke.omoteniola@palmpay-inc.com
            yakubu.kamilah@palmpay-inc.com
            fang.yang@palmpay-inc.com
            agunloye.raphael@palmpay-inc.com
            precious.ike@palmpay-inc.com
            okafor.joy@palmpay-inc.com
            bosu.medese@palmpay-inc.com
            doris.donatus@palmpay-inc.com
            ajayi.abiodun@palmpay-inc.com
            promise.ukpong@palmpay-inc.com
            jane.emeana@palmpay-inc.com
            rahman.oluwatoyin@palmpay-inc.com
            simbiat.kehinde@palmpay-inc.com
            asuelimen.marian@palmpay-inc.com
            joseph.cletus@palmpay-inc.com
            maryam.moshood@palmpay-inc.com
            tinuola.fasehun@palmpay-inc.com
            bolude.ifeolu@palmpay-inc.com
            regina.okposong@palmpay-inc.com
            odianose.stella@palmpay-inc.com
            esekwe.nneka@palmpay-inc.com
            onyinyechi.emezue@palmpay-inc.com
            agbooro.helen@palmpay-inc.com
            okpechi.chidinma@palmpay-inc.com
            yuanyuan.xia@palmpay-inc.com
            stephanie.braimah@palmpay-inc.com
            vincent.awulu@palmpay-inc.com
            david.sikiru@palmpay-inc.com
            adewunmi.akinladenu@palmpay-inc.com
            bamidele.oluwamayomikun@palmpay-inc.com
            comfort.Monday@palmpay-inc.com
            ebelebe.mabel@palmpay-inc.com
            harry.etim@palmpay-inc.com
            lois.sunday@palmpay-inc.com
            mariam.oyeleke@palmpay-inc.com
            ogunniyi.olalekan@palmpay-inc.com
            badejo.faosiyah@palmpay-inc.com
            daniella.richard@palmpay-inc.com
            olaiya.olayinka@palmpay-inc.com
            patience.ogini@palmpay-inc.com
            francis.abaji@palmpay-inc.com
            stanley.ezeh@palmpay-inc.com
            ifeoluwa.osobisi@palmpay-inc.com
            mary.isoje@palmpay-inc.com
            shofolabo.catherine@palmpay-inc.com
            tosin.omoolofin@palmpay-inc.com
            dawei.zhang@palmpay-inc.com
            Olagoro.gbemisola@palmpay-inc.com
            cynthia.ogudu@palmpay-inc.com
            ekile.chinedu@palmpay-inc.com
            onanuga.oluwatobi@palmpay-inc.com
            onyeche.jennifer@palmpay-inc.com
            hassan.tolulope@palmpay-inc.com
            ajobi.abraham@palmpay-inc.com
            bukola.taiwo@palmpay-inc.com
            damilola.awobona@palmpay-inc.com
            osungbayi.veronica@palmpay-inc.com
            kehinde.olufowokan@palmpay-inc.com
            michael.segun@palmpay-inc.com
            Olamiposi.Olayemi@palmpay-inc.com
            kalu.chinenye@palmpay-inc.com
            shuqi.hu@palmpay-inc.com
            henry.adoga@palmpay-inc.com
            blessing.ajiroba@palmpay-inc.com
            ibe.chinonso@palmpay-inc.com
            Siyanbola.emmanuel@palmpay-inc.com
            johnson.adebayo@palmpay-inc.com
            jinyan.li@palmpay-inc.com
            ogechi.ozoemene@palmpay-inc.com
            obu.chukwuemelie@palmpay-inc.com
            fashoyin.dunbarin@palmpay-inc.com
            salaudeen.omolabake@palmpay-inc.com
            adekoya.taiwo@palmpay-inc.com
            agaba.chinaza@palmpay-inc.com
            blessing.chami@palmpay-inc.com
            esther.simon@palmpay-inc.com
            Badmus.hajarah@palmpay-inc.com
            abraham.aladeokin@palmpay-inc.com
            Alika.Hope@palmpay-inc.com
            Muhammed.Suleiman@palmpay-inc.com
            nathaniel.orji@palmpay-inc.com
            opeyemi.bosu@palmpay-inc.com
            salau.bashir@palmpay-inc.com
            sehinde.kolawole@palmpay-inc.com
            tajudeen.abdullahi@palmpay-inc.com
            uruakpa.onyebuchi@palmpay-inc.com
            afolabi.waheedat@palmpay-inc.com
            jiaqi.xu@palmpay-inc.com
            bodunde.victor@palmpay-inc.com
            peter.adewale@palmpay-inc.com
            alese.kanashi@palmpay-inc.com
            fatimoh.martins@palmpay-inc.com
            qifeng.hou@palmpay-inc.com
            adedoyin.solomon@palmpay-inc.com
            ojo.omolola@palmpay-inc.com
            ibidun.salawu@palmpay-inc.com
            oluwadamilola.owolabi@palmpay-inc.com
            Oluwaseun.ojo@palmpay-inc.com
            adewunmi.ajala@palmpay-inc.com
            efeturi.idogun@palmpay-inc.com
            emeka.esther@palmpay-inc.com
            oluwaseye.esther@palmpay-inc.com
            victor.olawoyin@palmpay-inc.com
            akinwunmi.kayode@palmpay-inc.com
            latinwo.saheed@palmpay-inc.com
            ping.yu@palmpay-inc.com
            Oluwabunmi.omoniyi@palmpay-inc.com
            yunqiu.zhao@palmpay-inc.com
            esther.onwubolu@palmpay-inc.com
            zerui.sun@palmpay-inc.com
            Daniel.celestine@palmpay-inc.com
            obodo.winifred@palmpay-inc.com
            yetunde.abubakar@palmpay-inc.com
            akinbade.latifat@palmpay-inc.com
            bamitale.akilo@palmpay-inc.com
            olayemi.omotola@palmpay-inc.com
            aweda.oluwatobiloba@palmpay-inc.com
            ukachukwu.chisom@palmpay-inc.com
            akinlolu.emmanuel@palmpay-inc.com
            emmanuel.umoh@palmpay-inc.com
            esther.zedomi@palmpay-inc.com
            victor.nnaji@palmpay-inc.com
            obehi.stanley@palmpay-inc.com
            akabogu.gertrude@palmpay-inc.com
            monitor.office@palmpay-inc.com
            edem-orok.ruth@palmpay-inc.com
            osho.jacob@palmpay-inc.com
            atitiuwa.erhun@palmpay-inc.com
            chukwu.blessing@palmpay-inc.com
            hao.jiang@palmpay-inc.com
            gaochao.zheng@palmpay-inc.com
            oyeyipo.kanyinsola@palmpay-inc.com
            osuji.olamilekan@palmpay-inc.com
            harmony.hycienth@palmpay-inc.com
            ifunanya.abugu@palmpay-inc.com
            racheal.osiogo@palmpay-inc.com
            adelaja.aina@palmpay-inc.com
            samuel.olumofe@palmpay-inc.com
            zhonghui.cao@palmpay-inc.com
            patrick.aninye@palmpay-inc.com
            justina.jackto@palmpay-inc.com
            yang.yang@palmpay-inc.com
            idowu.oluwatobiloba@palmpay-inc.com
            kabiru.yusuf@palmpay-inc.com
            jing.zhu@palmpay-inc.com
            ferdinald.emeodi@palmpay-inc.com
            quancheng.zhao@palmpay-inc.com
            idris.abdullahi1@palmpay-inc.com
            funmi.banjo@palmpay-inc.com
            ojo.babatunde@palmpay-inc.com
            doyinsola.joseph@palmpay-inc.com
            Patience.udom@palmpay-inc.com
            olowoyo.taiwo@palmpay-inc.com
            adetu.olaide@palmpay-inc.com
            ojo-ogun.olawale@palmpay-inc.com
            pascal.obitor@palmpay-inc.com
            Sonola.Funmilayo@palmpay-inc.com
            liuqing.guo@palmpay-inc.com
            linda.ngwu@palmpay-inc.com
            adeyemo.noah@palmpay-inc.com
            joel.onanug@palmpay-inc.com
            bunmi.adeniyi@palmpay-inc.com
            danyang.wei@palmpay-inc.com
            akpan.mabel@palmpay-inc.com
            agidee.temitope@palmpay-inc.com
            ojuolape.oladapo@palmpay-inc.com
            hao.sun@palmpay-inc.com
            winifred.vincent@palmpay-inc.com
            lawrence.odunlami@palmpay-inc.com
            taksing.poyi@palmpay-inc.com
            guanjun.feng@palmpay-inc.com
            james.idibia1@palmpay-inc.com
            mfonobong.orok@palmpay-inc.com
            fansmond.ajibade@palmpay-inc.com
            hongyun.lu@palmpay-inc.com
            ladipo.esther@palmpay-inc.com
            yifeng.xiao@palmpay-inc.com
            blessing.etim@palmpay-inc.com
            eleanya.precious@palmpay-inc.com
            ezenwilo.vivian@palmpay-inc.com
            oladiji.ayodele@palmpay-inc.com
            toluwalase.ibimiluyi@palmpay-inc.com
            zulihat.yahaya@palmpay-inc.com
            busheng.zhang@palmpay-inc.com
            iloegbu.ifeoma@palmpay-inc.com
            olaide.owolabi@palmpay-inc.com
            jing.wang@palmpay-inc.com
            yuguo.zhang@palmpay-inc.com
            blessing.edwards@palmpay-inc.com
            jiajun.sun@palmpay-inc.com
            eniola.taiwo@palmpay-inc.com
            adeniji.bukola@palmpay-inc.com
            zhuoer.wang@palmpay-inc.com
            yukun.ding@palmpay-inc.com
            anna.oyedo@palmpay-inc.com
            ekwu.constantine@palmpay-inc.com
            rosemary.onabanjo@palmpay-inc.com
            francis.iwuoha@palmpay-inc.com
            henry.ndu@palmpay-inc.com
            ezeani.chizoba@palmpay-inc.com
            ishioma.millisent@palmpay-inc.com
            Olukayode.Olusegun@Palmpay-inc.com
            ya.xu@palmpay-inc.com
            jiangling.cao@palmpay-inc.com
            folarin.yetunde@palmpay-inc.com
            gang.chen@palmpay-inc.com
            foladivinesuccess@gmail.com
            anigbo.olivia@palmpay-inc.com
            bamidele.sunday@palmpay-inc.com
            courage.yaweagbe@palmpay-inc.com
            emmanuel.ugbe@palmpay-inc.com
            emmanuel.ugochukwu@palmpay-inc.com
            habib.jibril@palmpay-inc.com
            judith.ogbolu@palmpay-inc.com
            Mohammed.salawu@palmpay-inc.com
            nsikakabasi.akpabio@palmpay-inc.com
            tosin.ajayi@palmpay-inc.com
            adewunmi.oluseyi@palmpay-inc.com
            onu.chioma@palmpay-inc.com
            oshin.olayemi@palmpay-inc.com
            owolabi.itunuoluwa@palmpay-inc.com
            segun.adeyemi@palmpay-inc.com
            feiyin.yang@palmpay-inc.com
            yan.qiao@palmpay-inc.com
            precious.okoro@palmpay-inc.com
            kaiwen.zhou@palmpay-inc.com
            bathsheba.nzogilonge@palmpay-inc.com
            doowuese.age@palmpay-inc.com
            ebenezar.dada@palmpay-inc.com
            ideyi.peace@palmpay-inc.com
            jemimah.mainasara@palmpay-inc.com
            Kayode.olumofe@palmpay-inc.com
            matti.omotoyosi@palmpay-inc.com
            musa.farouk@palmpay-inc.com
            olotu.babajide@palmpay-inc.com
            paul.faith@palmpay-inc.com
            rossy.akut@palmpay-inc.com
            ngozi.leonard@palmpay-inc.com
            feng.lin@palmpay-inc.com
            omoarelemi.joy@palmpay-inc.com
            junyu.di@palmpay-inc.com
            oyeleke.blessing@palmpay-inc.com
            xinquan.lin@palmpay-inc.com
            feixiang.zhang@palmpay-inc.com
            ayomide.shofolabo@palmpay-inc.com
            haoqi.feng@palmpay-inc.com
            xinyu.wang@palmpay-inc.com
            omeniru.precious@palmpay-inc.com
            adagba.joseph@palmpay-inc.com
            fayemi.akinwale@palmpay-inc.com
            gift.nwaokolo@palmpay-inc.com
            ini.joy@palmpay-inc.com
            Ojong.elkanah@palmpay-inc.com
            olaitan.afeez@palmpay-inc.com
            shelu.omuna@palmpay-inc.com
            afamefuna.onyeka@palmpay-inc.com
            oladipupo.yusuf@palmpay-inc.com
            abiodun.jokotola@palmpay-inc.com
            Oduneye.Olufunsho@palmpay-inc.com
            osadare.abiola@palmpay-inc.com
            opeyemi.castro@palmpay-inc.com
            bingyu.guan@palmpay-inc.com
            kingsleyiheagwam@opay-inc.com
            qiangqiang.li@palmpay-inc.com
            yicheng.li@palmpay-inc.com
            ajewole.fisayo@palmpay-inc.com
            siyanbola.solomon@palmpay-inc.com
            Muhammed.ridwan@palmpay-inc.com
            juan.zhao@palmpay-inc.com
            ruiqian.chen@palmpay-inc.com
            yangtong.chen@palmpay-inc.com
            adeboye.babatunde@palmpay-inc.com
            oluwayomi.alabi@palmpay-inc.com
            adeniran.abidemi@palmpay-inc.com
            adu.oluwatosin@palmpay-inc.com
            anutomi.olorundare@palmpay-inc.com
            babatunde.ibitola@palmpay-inc.com
            damilola.idowu@palmpay-inc.com
            deborah.mukan@palmpay-inc.com
            ibrahim.adepoju@palmpay-inc.com
            jerry.ijezie@palmpay-inc.com
            owolebi.taiwo@palmpay-inc.com
            precious.chiedozie@palmpay-inc.com
            talabi.elizabeth@palmpay-inc.com
            yeting.zeng@palmpay-inc.com
            cuimei.li@palmpay-inc.com
            dongliang.zhang@palmpay-inc.com
            li.zhu@palmpay-inc.com
            yihe.zhang@opay-inc.com
            junwei.chen@palmpay-inc.com
            buraimoh.esther@palmpay-inc.com
            Vitalis.muo@palmpay-inc.com
            yue.yang@palmpay-inc.com
            john.agbola@palmpay-inc.com
            yang.yang1@palmpay-inc.com
            di.wan@palmpay-inc.com
            amos.bazo@palmpay-inc.com
            etidobasi.effa@palmpay-inc.com
            hammeed.seleem@palmpay-inc.com
            kennedy.okereke@palmpay-inc.com
            kenneth.ukattah@palmpay-inc.com
            ogochukwu.blessing@palmpay-inc.com
            ugwuamadi.chinecherem@palmpay-inc.com
            juanmin.chen@palmpay-inc.com
            effiong.afaha@palmpay-inc.com
            adegelu.esther@palmpay-inc.com
            Ogundare.micheal@palmpay-inc.com
            umezurike.chiamaka@palmpay-inc.com
            xingpeng.yuan@palmpay-inc.com
            shedrach.okafor@palmpay-inc.com
            jianqiang.huang@palmpay-inc.com
            taili.liu@palmpay-inc.com
            wisdom.chukwudume@palmpay-inc.com
            abodesegun.emmanuel@palmpay-inc.com
            asubiojo.samuel@palmpay-inc.com
            john.jonathan@palmpay-inc.com
            stephen.audu@palmpay-inc.com
            junke.dou@palmpay-inc.com
            xiaogang.zhang@palmpay-inc.com
            changcai.duan@palmpay-inc.com
            wenlong.jia@palmpay-inc.com
            jian.zou@palmpay-inc.com
            jiajin.dong@palmpay-inc.com
            yu.he@palmpay-inc.com
            okeke.chinwendu@palmpay-inc.com
            woluchem.mildred@palmpay-inc.com
            bo.yin@palmpay-inc.com
            madu.bright@palmpay-inc.com
            pengtong.weng@palmpay-inc.com
            ping.wang@palmpay-inc.com
            """;

    @Test
    void test1() {
        EdsConfigs.Dingtalk dingtalk = getConfig(43);
        DingtalkDepartmentModel.GetDepartmentResult result = dingtalkDepartmentRepo.get(dingtalk,
                DingtalkDepartmentParam.GetDepartment.builder()
                        .build());
        System.out.println(result);
    }

    @Resource
    private EdsAssetIndexService indexService;
    @Resource
    private EdsAssetService assetService;

    @Test
    void test2() {
        Iterable<String> list = Splitter.on("\n")
                .split(MAIL_LIST);
        list.forEach(oMail -> {
            String mail = oMail.trim();
            // 查询索引
            System.out.println("正在解析: " + mail.trim());
            List<EdsAssetIndex> indices = indexService.queryIndexByNameAndValue(USER_MAIL, mail);
            for (EdsAssetIndex index : indices) {
                EdsAsset asset = assetService.getById(index.getAssetId());


            }

        });
    }

}

