package com.baiyi.cratos.common.constants;

/**
 * &#064;Author  baiyi
 * &#064;Date  2024/12/5 09:52
 * &#064;Version 1.0
 */
public interface SchedulerLockNameConstants {

    String INSPECTION_NOTIFICATION_TASK = "INSPECTION_NOTIFICATION_TASK";
    String IMPORT_OC_APPLICATION_TASK = "IMPORT_OC_APPLICATION_TASK";
    String REVOKING_PERMISSIONS_FOR_RESIGNED_USERS_TASK = "REVOKING_PERMISSIONS_FOR_RESIGNED_USERS_TASK";
    String SCAN_ALL_APPLICATION_RESOURCES_TASK = "SCAN_ALL_APPLICATION_RESOURCES_TASK";
    String SCAN_ALL_APPLICATION_RESOURCE_BASELINE_TASK = "SCAN_ALL_APPLICATION_RESOURCE_BASELINE_TASK";
    String SCAN_ALL_APPLICATION_ACTUATOR_TASK = "SCAN_ALL_APPLICATION_ACTUATOR_TASK";
    String DO_COMMAND_EXEC = "DO_COMMAND_EXEC";

}
