package com.baiyi.cratos.workorder.enums;

/**
 * &#064;Author  baiyi
 * &#064;Date  2025/3/19 13:52
 * &#064;Version 1.0
 */
public enum WorkOrderKeys {

    APPLICATION_PERMISSION,
    APPLICATION_PROD_PERMISSION,
    APPLICATION_TEST_PERMISSION,

    APPLICATION_FRONTEND_CREATE,

    COMPUTER_PERMISSION,
    SERVER_ACCOUNT_PERMISSION,
    APPLICATION_ELASTIC_SCALING,
    APPLICATION_DEPLOYMENT_SCALE,
    REVOKE_USER_PERMISSION,
    GITLAB_PROJECT_PERMISSION,
    GITLAB_GROUP_PERMISSION,
    ALIYUN_DATAWORKS_AK,
    ALIYUN_KMS_SECRET_CREATE,
    ALIYUN_KMS_SECRET_UPDATE,
    NEXUS_PERMISSION,
    APPLICATION_DELETE_POD,
    LDAP_ROLE_PERMISSION,

    ALIYUN_RAM_USER_PERMISSION,
    ALIYUN_RAM_POLICY_PERMISSION,
    ALIYUN_RAM_USER_RESET,

    ALIYUN_ONS_TOPIC,
    ALIYUN_ONS_CONSUMER_GROUP,

    ALIMAIL_USER_RESET,

    AWS_IAM_USER_RESET,
    AWS_TRANSFER_SFTP_USER_PERMISSION,
    AWS_IAM_POLICY_PERMISSION,

    RISK_CHANGE

}
