package com.baiyi.cratos.common.enums;

/**
 * &#064;Author  baiyi
 * &#064;Date  2025/2/24 15:56
 * &#064;Version 1.0
 */
public enum NotificationTemplateKeys {

    DOMAIN_EXPIRATION_INSPECTION_NOTIFICATION,
    CERTIFICATE_EXPIRATION_INSPECTION_NOTIFICATION,
    DEPLOYMENT_GROUP_LABEL_INSPECTION_NOTIFICATION,
    APPLICATION_GROUPING_COMPLIANCE_INSPECTION_NOTIFICATION,
    CUSTOM_ASSET_EXPIRATION_INSPECTION_NOTIFICATION,
    APPLICATION_DEPLOYMENT_IMAGE_COMPLIANCE_INSPECTION_NOTIFICATION,
    KUBERNETES_ELASTIC_WORKER_INSPECTION_NOTIFICATION,
    RESIGNATION_USERS_INSPECTION_NOTIFICATION,

    COMMAND_EXEC_APPROVAL_NOTICE,
    COMMAND_EXEC_APPROVAL_RESULT_NOTICE,
    // WorkOrder
    WORK_ORDER_TICKET_APPROVAL_NOTICE,
    WORK_ORDER_COMPLETION_NOTICE,
    CREATE_ALIYUN_DATAWORKS_RAM_AK_NOTICE,
    CREATE_ALIYUN_RAM_USER_NOTICE,
    RESET_ALIYUN_RAM_USER_NOTICE,
    RESET_ALIMAIL_USER_NOTICE,
    USER_RESET_PASSWORD_NOTICE,
    CREATE_AWS_IAM_USER_NOTICE,
    RESET_AWS_IAM_USER_NOTICE,
    SSHSERVER_USER_LOGIN_SERVER_NOTICE,
    KUBERNETES_WSH_EXEC_NOTICE,
    CRYSTAL_USER_LOGIN_SERVER_NOTICE,
    NETWORK_INFO,

    DATA_SECURITY_ALERT_NOTICE,
    ZBX_ALERT_NOTIFICATION

}
